version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "3000:8080"  # Access frontend at http://localhost:3000
    env_file:
      - .env
    environment:
      - PORT=8080
      - AUTH_API_ADDRESS=${AUTH_API_ADDRESS}
      - TODOS_API_ADDRESS=${TODOS_API_ADDRESS}

  auth-api:
    build: ./auth-api
    ports:
      - "3001:8081"  # Access auth-api at http://localhost:3001
    env_file:
      - .env
    environment:
      - AUTH_API_PORT=8081
      - JWT_SECRET=${JWT_SECRET}
      - USERS_API_ADDRESS=${USERS_API_ADDRESS}

  todos-api:
    build: ./todos-api
    ports:
      - "3002:8082"  # Access todos-api at http://localhost:3002
    env_file:
      - .env
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_CHANNEL=${REDIS_CHANNEL}

  users-api:
    build: ./users-api
    ports:
      - "3003:8083"  # Access users-api at http://localhost:3003
    env_file:
      - .env
    environment:
      - SERVER_PORT=8083
      - JWT_SECRET=${JWT_SECRET}

  log-message-processor:
    build: ./log-message-processor
    env_file:
      - .env
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_CHANNEL=${REDIS_CHANNEL}

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes

networks:
  default:
    driver: bridge
